name: flutter_adaptive_layout_kit
description: "A Flutter package for building adaptive layouts and responsive UIs with ease. Provides utilities for adaptive layouts, text, and grid systems. Internally uses the sizer package for screen measurements, which is managed by the library."
version: 0.0.2
homepage: https://github.com/Edwin-sh/flutter_adaptive_layout_kit
repository: https://github.com/Edwin-sh/flutter_adaptive_layout_kit
issue_tracker: https://github.com/Edwin-sh/flutter_adaptive_layout_kit/issues

environment:
  sdk: ^3.7.2 # Ensure this is compatible with your Flutter version and sizer
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^3.0.5 # Keep sizer as a dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
