name: flutter_responsive_ui
description: "A Flutter package for building responsive and adaptive UIs with ease. Provides utilities for responsive layouts, text, and grid systems. Internally uses the sizer package for screen measurements, which is managed by the library."
version: 0.0.1
homepage: # TODO: Replace with your GitHub repository URL
repository: # TODO: Replace with your GitHub repository URL (e.g., https://github.com/your_username/flutter_responsive_ui)
issue_tracker: # TODO: Replace with your GitHub issue tracker URL (e.g., https://github.com/your_username/flutter_responsive_ui/issues)

environment:
  sdk: ^3.7.2 # Ensure this is compatible with your Flutter version and sizer
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^3.0.5 # Keep sizer as a dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
